### ISSUE TITLE
RRHO2_heatmap doesn't "close" the layout it generates

### ISSUE THREAD

**Issue by gdevenyi** [RRHO2/RRHO2#10]
If I try to use RRHO2_vennDiagram after RRHO2_heatmap, the venn diagram ends up inside the heatmap's colourbar:
![image](https://user-images.githubusercontent.com/3001850/93965288-c21a1180-fd2f-11ea-88c7-9d1928629876.png)

**Comment by gdevenyi** [comment]
Workaround is to purge my open figures first.

**Comment by gdevenyi** [comment]
This also happens for vennDiagram figures:
![image](https://user-images.githubusercontent.com/3001850/93965345-eb3aa200-fd2f-11ea-8474-68c8a4d0aa21.png)

**Comment by Caleb-Huo** [comment]
Thanks again for reporting this.
Should have fixed this bug.

**Comment by gdevenyi** [comment]
Hi, the venn diagrams still draw on top of each other.
