### ISSUE TITLE
NA value and Rank metric

### ISSUE THREAD

**Issue by sumitpaliwal** [RRHO2/RRHO2#11]
Hi,
I have performed differential expression analysis for two datasets and now want to compare the overlap between the differentially expressed genes. However I have several doubts/issues regarding the usage.
1. Should the two gene lists that I intend to compare have identical number of genes?
2. Should the order of genes be the same?
3. When I use
`RRHO2_initialize(list1, list2 labels = c("list1", "list2"), log10.ind=TRUE)`
I get the error
> NA value exists in list1, please remove them.

This is because, for several genes, pvalue = NA. Similar would be the case if I use a ranking metric [-log10(P-value) * sign(effect)]. I do not know how to deal with this.

**Comment by Caleb-Huo** [comment]
Hi there:

1, The two gene lists should have identical number of genes.
2, The order go genes can be different.
3, RRHO won't interpret pvalue=NA, so you may want to remove genes with pvalue=NA.

Let me know if these can help solve the problem.
Thanks for your question, and I will try to improve the tutorial based on your question.

**Comment by sumitpaliwal** [comment]
Hi,
Thanks for the reply.
The two gene lists in question can have different number of genes that have pvalue=NA. If I remove those genes, then there is possibility that the two lists will not be identical for the number of genes. How do I deal with this?

Sumit

**Comment by Caleb-Huo** [comment]
@sumitpaliwal 
In this case, you might need to remove those genes uniquely belong to one dataset.
RRHO will only use non-missing genes existing in both datasets to generate the heatmap.

**Comment by sumitpaliwal** [comment]
Hi Caleb,
Thanks a lot. The analysis is working now and I got a nice plot. Only a couple of things more to resolve. 
1. I am not getting the scale bar along with the plot.
2. In R studio, I get the following error:
`Error in plot.new() : figure margins too large`

Is there a way to directly save this plot to a file.

Sumit

**Comment by Caleb-Huo** [comment]
Hi Sumit:

1, I tried the example code, and I could obtain the scale bar along with the plot.
Did you try the example code? If it also works, then I will look deeper into your code.

2, Here are some online tutorials about how to save plot in R:
https://www.datamentor.io/r-programming/saving-plot/

Hope these may help.

Best,

Caleb

**Comment by sumitpaliwal** [comment]
Hi Caleb,
I do not get the scale bar even when I run the example code.

Thanks,
Sumit

**Comment by sumitpaliwal** [comment]
Hi Caleb,
The issue is resolved. I can see the scale bar when I save the plot directly to a file.
Thanks again.

Sumit

**Comment by Caleb-Huo** [comment]
Hi Sumit:

Thanks for letting me know, and thanks for using RRHO2.

Best,

Caleb
