### ISSUE TITLE
Non-unique gene identifier found in list2

### ISSUE THREAD

**Issue by matthew-paul-2006** [RRHO2/RRHO2#6]
Hi there,

I kept getting the error message regardless of what I did when I initialize. 
"Non-unique gene identifier found in list2"

Looking at your code for the function I think I can see the cause (if I am understanding it correctly).

In line 57 you are checking for duplicated gene IDs, but you are checking within the DDE column of the first list, as opposed to the gene ID column of the second list. 

If I remove any duplicate DDE values from list1, it initializes fine, so I'm pretty sure that is the culprit. 

Cheers,
Matt

**Comment by Caleb-Huo** [comment]
Hi Matt:

Thanks for reporting the bug, and helping identify the issue.
I should have fixed the bug at line 57.

To use the updated function, please re-install the package, and re-start R.

Cheers,

Caleb

**Comment by matthew-paul-2006** [comment]
Thanks for the quick fix. and for your recent update. It really makes the package more user friendly.
