### ISSUE TITLE
Multiple testing

### ISSUE THREAD

**Issue by matthew-paul-2006** [RRHO2/RRHO2#7]
Hi again,

Either a feature request or maybe it is something I missed. 

I know the original RRHO package on bioconductor offered multiple testing correction with BH. Did I miss this, or is this something you are going to add at any point. 

Cheers,
Matt

**Comment by Caleb-Huo** [comment]
Hi Matt:

Thanks for having this suggestion.
I added multipleTesting argument in the RRHO_initialize function.
It can be set to "none" (raw-pvalue), "BH" (suggested by you), and "BY" (suggested by the original RRHO package).

Cheers,

Caleb

**Comment by matthew-paul-2006** [comment]
Fantastic. Thank you. I think I got my wires crossed between my Benjamini corrections. Thanks for adding both!

**Comment by DelongZHOU** [comment]
Hello,

I encountered the following error when I tried to use either BH or BY correction:

```
Error in seq.default(minimum, maximum, length.out = length(colorGradient) +  :
  'to' must be a finite number
In addition: Warning message:
In RRHO2_initialize(psy_l2fc_reduce, stress_l2fc_reduce, labels = c("Psy.F",  :
  Inf was generated because of the multiple testing procedure. I.e., the multiple testing procedure cannot handle extreme small p-values. Suggest to use raw p-value (multipleTesting='none')
```

I do get pval up to 10e-600 without the correction. Is there a way to deal with this?
Thank you!
