### ISSUE TITLE
jet/rainbow colourmap considered harmful

### ISSUE THREAD

**Issue by gdevenyi** [RRHO2/RRHO2#8]
There's of lots of discussions on this in many places, but here's one version https://blogs.egu.eu/divisions/gd/2017/08/23/the-rainbow-colour-map/

I'd like to request either control of the heatmap colourmap, or a change to virdis[1] as the default.

[1] https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html

**Comment by Caleb-Huo** [comment]
This is very educational to me. 

Should have given control of the heatmap colourmap, see example below.
RRHO2_heatmap(RRHO_obj, colorGradient =  gplots::bluered(101))

Just in case, you can also obtain the heatmap matrix by 
RRHO_obj$hypermat

**Comment by sadinoj** [comment]
Hi, 
  I know that this question has closed but I am currently trying to change the color gradient of the RRHO2 heatmap. I have tried using colorGraident = but I get an error that says it is not a graphical parameter. I installed the most recent version of RRHO2 from GitHub and am still having the same issue. Thanks for your help. 
  JS

**Comment by Caleb-Huo** [comment]
Hi:

I just tested, and it worked on my computer.
Could you provide more details? I.e., are you able to use colorGradient
using the RRHO2_heatmap default example?

Caleb

**Comment by gdevenyi** [comment]
yes, your suggestions worked for me thanks

**Comment by sadinoj** [comment]
Hi Caleb, 
  I apologize, I deleted my comment because I ended up figuring it out. RRHO2 was the most recent version but I had to update everything else in my environment and then it became an option. Thank you for getting back to me! 
  JS
